// ~~ Generated by projen. To modify, edit .projenrc.ts and run "pnpm --silent dlx projen".
import type { ProjenTypeScriptWorkspacePackages } from '@scaleleap/projen-project-typescript'
declare module '@scaleleap/projen-project-typescript' {
  interface ProjenTypeScriptWorkspacePackages {
    "@boilerkit/tpl": 1;
  }
}