// ~~ Generated by projen. To modify, edit .projenrc.ts and run "projen".
import type { ProjenTypeScriptWorkspacePackages } from '@scaleleap/projen-typescript-base-project'
declare module '@scaleleap/projen-typescript-base-project' {
  interface ProjenTypeScriptWorkspacePackages {
    "@boilerkit/cli": 1;
    "@boilerkit/core": 1;
    "@boilerkit/tpl": 1;
    "@boilerkit/types": 1;
    "docs": 1;
  }
}