// ~~ Generated by projen. To modify, edit .projenrc.js and run "pnpm --silent dlx projen".
import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [
    react(),
  ],
})