// ~~ Generated by projen. To modify, edit .projenrc.js and run "projen".
import React from 'react'
import ReactDOM from 'react-dom/client'

import { App } from './App'

const rootElement = document.querySelector('#root')

if (!rootElement) {
  throw new Error('Cannot find #root element.')
}

ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
