// ~~ Generated by projen. To modify, edit .projenrc.js and run "projen".
import { defineConfig } from 'vitest/config'
import isCi from 'is-ci'
import GithubActionsReporter from 'vitest-github-actions-reporter'
import tsconfigPaths from 'vite-tsconfig-paths'
export default defineConfig({
  plugins: [
    tsconfigPaths()
  ],
  test: {
    reporters: process.env.GITHUB_ACTIONS ? ['default', new GithubActionsReporter()] : 'default',
    passWithNoTests: true,
    globals: true,
    update: !isCi,
    include: ["src/**/*.test.ts?(x)","test/**/*.test.ts?(x)"],
  },
})