// ~~ Generated by projen. To modify, edit .projenrc.js and run "pnpm --silent dlx projen".
import { defineConfig } from 'vitest/config'
import tsconfigPaths from 'vite-tsconfig-paths'
export default defineConfig({
  plugins: [
    tsconfigPaths()
  ],
  test: {
    globals: true,
    include: ["src/**/*.test.ts?(x)","test/**/*.test.ts?(x)"],
  },
})